xmqb/urls.py
# -*- coding: UTF-8 -*-

from django.conf.urls import url
from django.contrib import admin
from webuser.views import index, weblogin,register,profile,project,delete_project,pay,create_project,uploadify_script,profile_delte,Change_Passwords,Change_project
from django.contrib.auth.views import logout
from adminuser import views as admin_views
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^weblogin/$', weblogin, name='weblogin'),
    url(r'^register/$', register, name='register'),
    url(r'^admin', admin.site.urls),
    url(r'^person/$', profile, name='profile'),
    url(r'^project/$', project, name='project'),
    url(r'^delete_project/$', delete_project, name='delete_project'),
    url(r'^create_project/$', create_project, name='create_project'),
    url(r'^pay/$', pay, name='pay'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    # Here is a method of using url : url( r'...',method_name,arguments_or_just_one_argument_in_this_method_interface,name=.....)
    # So this kind of usage is similar with method like $post('url_in_this_file',{....:.....,.....:......}) in jquery
    # Seems like in django , if you want to transmit arguments to a method , you do not have to add strings like '...../&...='+''+.....
    # This just cost too much time , so just use a dictionary to match argument
    url(r'^uploadify_script/$', uploadify_script, name='upload_script'),
    url(r'^delete_uploadfile/$', profile_delte, name='profile_delte'),
    url(r'^change_passwords/$',Change_Passwords,name='change_passwords'),
    url(r'^change_project/$',Change_project,name='change_project'),
    url(r'^admin_people/$',admin_views.super_profile,name='admin_people'),
    url(r'^user_manage/$',admin_views.users,name='admin_people'),
    url(r'^delete_user/$',admin_views.delete_user,name='delete_user'),
    url(r'^person_change/$',admin_views.change_user,name='person_chagne'),
    url(r'^super_pay_manage/$',admin_views.pay,name='super_pay_manage'),

    # Function changing any user password , changing pay status and delete deal for admin user
    url(r'^super_change_password/$',admin_views.Super_Change_Passwords,name='super_change_password'),
    url(r'^super_change_pay/$',admin_views.Super_Change_pay,name='super_change_pay'),
    url(r'^deleat_pay/$',admin_views.deal_delete,name='delete_pay'),

]

webuser/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.


class Webuser(models.Model):
    user = models.OneToOneField(User)
    name = models.CharField(max_length=10, null=True, blank=True)
    hospital = models.CharField(max_length=20, null=True, blank=True)
    position = models.CharField(max_length=10, null=True, blank=True)
    department = models.CharField(max_length=10, null=True, blank=True)
    telephone = models.CharField(max_length=20, null=True, blank=True)
    abstract = models.TextField(max_length=100, null=True, blank=True)

    def __unicode__(self):
        return self.user.username

class Project(models.Model):
    user = models.ForeignKey(User)
    Order_ID =  models.CharField(primary_key=True,max_length=30, null=False, blank=False)
    name = models.CharField(max_length=50, null=True, blank=True)
    classify = models.CharField(max_length=10, null=True, blank=True)
    upload_dir = models.CharField(max_length=5000, null=True, blank=True)
    create_time = models.DateTimeField(auto_now_add=True)
    status =models.BooleanField(default=False)
    remark = models.TextField(max_length=100, null=True)
    def __unicode__(self):
        return self.user.username

class UploadFile(models.Model):
    user = models.ForeignKey(User)
    Order_ID =  models.ForeignKey(Project)
    directory = models.CharField(primary_key=True,max_length=100, null=False, blank=False)
    upload_time = models.DateTimeField(auto_now_add=True)
    def __unicode__(self):
        return self.user.username

class Pay(models.Model):
    project = models.OneToOneField(Project)
    user = models.ForeignKey(User)
    is_pay = models.BooleanField(default=False)
    price = models.CharField(max_length=10, null=True, blank=True)

    def __unicode__(self):
        return self.user.username

webuser/forms.py
#coding=utf-8

from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django import forms
from django.contrib import auth
from .models import Webuser,Project,Pay
from django.utils.safestring import mark_safe


class HorizontalRadioRenderer(forms.RadioSelect.renderer):      #水平单选框水平样式
    def render(self):
        return mark_safe(u'\n'.join([u'&nbsp;&nbsp;&nbsp;%s\n ' % w for w in self]))


class LoginForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                               max_length=30, required=True, label=u'用户名', error_messages={'required': u'用户名不能为空'})
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               label=u'密码', error_messages={'required': u'密码不能为空'},
                               required=True)

    # 上面主要是对样式的覆盖，不用其实也行，只不过很多想要的效果会消失，比如自定义的错误提示等

    class Meta:  # 和数据模型关联类ModelForm必要的子类
        model = User
        fields = ['username', 'password']
        exclude = ['last_login', 'date_joined', 'email', 'confirm_password']  # 剔除不要的表项

    def __init__(self, *args, **kwargs):  # 初始化的方法
        super(LoginForm, self).__init__(*args, **kwargs)

    def clean(self):  # 提示账号密码错误的方法，并且清除内容
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if username and password:
            self.user_cache = auth.authenticate(username=username, password=password)
            if self.user_cache is None:
                self._errors['username'] = self.error_class([u'账号密码不匹配'])
        return self.cleaned_data


class RegisterForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                               max_length=30, required=True, label=u'用户名', error_messages={'required': u'用户名不能为空'})
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                           label=u'密码', error_messages={'required': u'密码不能为空'},
                           required=True)
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),
                               label=u'确认密码', error_messages={'required': u'密码不能为空'},
                               required=True)
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control'}),
                            required=True,
                            label=u'邮箱',error_messages={'required': u'邮箱不能为空'},
                            max_length=75)

    class Meta:  # 和数据模型关联类ModelForm必要的子类
        model = User
        fields = ['username', 'password','confirm_password','email']
        exclude = ['last_login', 'date_joined']  # 剔除不要的表项

    def __init__(self, *args, **kwargs):  # 初始化的方法
        super(RegisterForm, self).__init__(*args, **kwargs)

    def clean(self):   #自带的数据处理方法
        super(RegisterForm, self).clean()
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password and password != confirm_password:
            self._errors['password'] = self.error_class([u'密码不匹配'])
        return self.cleaned_data

class ProfileForm(forms.ModelForm):
    position_choice = ((u'0',u'医师'),(u'1',u'主任'),(u'2',u'病人'),(u'3',u'其他'))

    department_choice = (
    (u'0', u'呼吸内科'), (u'1', u'内分泌科'), (u'2', u'神经内科'), (u'3', u'肾内科'), (u'4', u'肝病研究所'), (u'5', u'中医科'), (u'6', u'骨肿瘤科'),(u'6', u'其他'))

    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                               max_length=20, required=True, label=u'姓名', error_messages={'required': u'姓名为必填项'})
    telephone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                               max_length=20, required=True, label=u'手机号码', error_messages={'required': u'手机号码为必填项'})
    hospital = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                               max_length=20, required=False, label=u'医院')
    position = forms.ChoiceField(label=u'职位', required=False, choices=position_choice)
    department = forms.IntegerField(widget=forms.RadioSelect(choices=department_choice,attrs={'class':'radio-inline'},renderer=HorizontalRadioRenderer),label=u'科室',
                                    error_messages={'required': u'请选择您的科室'})

    abstract = forms.CharField(label=u'简介',required=False,widget=forms.Textarea(attrs={'width':'900px','heigth':'1450px'}))

    class Meta:  # 和数据模型关联类ModelForm必要的子类
        model = Webuser
        fields = ['name', 'telephone', 'hospital', 'position', 'department', 'abstract']

class ProjectForm(forms.ModelForm):
    classify_choice = ((u'肝癌',u'肝癌'),(u'舌像',u'舌像'))
    Oder_id = forms.CharField(label='',required=False)
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}),
                           max_length=50, required=True, label=u'项目名称', error_messages={'required': u'项目名称不能为空'})
    dir = forms.CharField(label=u'请选择想要上传的文件',required=True,error_messages={'required': u'请选择上传文件'})
    classify = forms.ChoiceField(label=u'项目类型', required=True, choices=classify_choice)

    remark = forms.CharField(label=u'备注', required=False,
                             widget=forms.Textarea(attrs={'width': '900px', 'heigth': '1450px'}))

    class Meta:  # 和数据模型关联类ModelForm必要的子类
        model = Project
        fields = ['name', 'classify', 'remark']

class ChangePasswordForm(forms.Form):
    oldpassword=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),label=(u"原口令"),
                                max_length=300,required=True,error_messages={'required': u'请输入原始密码'})
    newpassword=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}),label=(u"新口令"),
                                max_length=300,required=True,error_messages={'required': u'请输入新密码'})
    newpassword1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=(u"新口令"),
                                  max_length=300,required=True,error_messages={'required': u'请再次输入新密码'})

webuser/templates/webuser/change_password.html
{% extends 'webuser/person_page.html' %}
{% block person_home_content %}
    <div class="col-md-6 container">
        <h1 class="page-header"><small>个人资料</small></h1>

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

            <form role="form" class="ProfileForm " method="post" role="form">
                  {% csrf_token %}
                <fieldset>
                    {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.label }}">{{ field.label }}</label>
          {{ field }}
          {% if field.help_text %}
            <span class="help-block">{{ field.help_text|safe }}</span>
          {% endif %}
          {% for error in field.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
      {% endfor %}
                </fieldset>

        <div class="form-group">
            <div  class="form-group-left">
              <button type="submit" class="btn btn-large btn-primary">提交修改</button>
              </div>
          </div>
             </form>
        </div>

{% endblock %}

webuser/templates/webuser/change_project.html
{% extends 'webuser/person_page.html' %}
{% block title %}个人主页个人资料页面{% endblock %}
{% block person_home_content %}
    <div class="col-md-6 container">
        <h1 class="page-header"><small>修改项目</small></h1>

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

            <form role="form" class="ProjectForm "  method="post" role="form">
            <div class="form-group" > 项目编号：{{ show_id }} </div>
                  {% csrf_token %}
                <fieldset>
                    {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.label }}">{{ field.label }}</label>
        {% if field.name == 'Oder_id' %}
            <div style="display: none;" >{{ field }}</div>
        {% elif field.name == 'dir'%}
          <div style="display: none;" >{{ field }}</div>
            <div class="demo-box">
    <input id="file_upload" type="file" name="Filedata">
    <div id="file_uploadQueue" class="uploadifyQueue"></div>
     <a href="javascript:$('#file_upload').uploadify('upload','*')">上传</a>
    <p><span id="id_span_msg"></span></p>
            </div>
         {% else %}
            {{ field }}
        {% endif %}
          {% if field.help_text %}
            <span class="help-block">{{ field.help_text|safe }}</span>
          {% endif %}
          {% for error in field.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
      {% endfor %}
        {% for field in form.visible_fields %}
                {% for error in field.errors %}
                    <script>
                 $("#id_dir").val("");
                    //这里的for循环就需要很注意，form表单展示出来的时候就是for循环，所以在for循环没循环到指定位置的时候，
                    //对这个指定位置所做的操作是无效的，比如这里，想要触发清空dir字段的操作，必须要在上面的for循环结束之后
                    //再做，因为就算是在for循环里dir字段之前的字段发生错误触发这个清空操作，dir字段的id是找不到的，因为它还没有
                    //被展示在网页里，所以只有在所有的filed展示出来，即以代码的形式通过for循环展示到网页中之后，定位dir字段id的
                    //的操作才会绝对有效
              </script>
                {% endfor %}
                {% endfor %}

                </fieldset>

        <div class="form-group">
            <div  class="form-group-left">
              <button type="submit" class="btn btn-large btn-primary">提交修改</button>

              </div>
          </div>

             </form>
        </div>
{% endblock %}

webuser/templates/webuser/login.html
{% extends "base.html" %}
{% block title %}登录{% endblock %}
{% block page_content %}

    <div id="mainbody">
         <div class="container">
            <h1 class="page-header">登录</h1>
             <div class="col-md-6">
             <form role="form" class="LoginForm" action="{% url 'weblogin' %}" method="post" role="form">
             <!--当点击提交时，触发weblogin 的方法-->
                  {% csrf_token %}
                <fieldset>
                    {% for field in form.visible_fields %}  <!--对于每一个field-->
        <div class="form-group{% if field.errors %} has-error{% endif %}"> <!--对表单进行排版-->
          <label for="{{ field.label }}">{{ field.label }}</label>  <!--将标签与modelform 内置标签对应起来-->
          {{ field }} <!--显示输入框 -->
          {% if field.help_text %}
            <span class="help-block">{{ field.help_text|safe }}</span> <!--如果有帮助提示，则显示-->
          {% endif %}
          {% for error in field.errors %}
            <label class="control-label">{{ error }}</label> <!--显示每个错误提示-->
          {% endfor %}
        </div>
      {% endfor %}

                </fieldset>

        <div class="form-group">
            <div  class="form-group-left">
              <button type="submit" class="btn btn-large btn-primary">提交</button>

              </div>
          </div>
             </form>

            </div>

         </div>
    </div>
    <!--主体内容结束-->

{% endblock %}

webuser/templates/webuser/pay_manage.html
{% extends 'webuser/person_page.html' %}
{% block title %}个人主页个人资料页面{% endblock %}
{% block person_home_content %}
    <style type="text/css">
table.gridtable {
	font-family: verdana,arial,sans-serif;
	font-size:11px;
	color:#333333;
	border-width: 1px;
	border-color: #666666;
	border-collapse: collapse;
}
table.gridtable th {
	border-width: 1px;
	padding: 10px;
	border-style: solid;
	border-color: #666666;
	background-color: #dedede;
}
table.gridtable td {
	border-width: 1px;
	padding: 8px;
	border-style: solid;
	border-color: #666666;
	background-color: #ffffff;
}
</style>
        <h1 class="page-header"><small>工程管理</small></h1>

     <table class="gridtable" cellpadding="0" cellspacing="0" >
                    <thead>
                    <tr>
                        <th>项目编号</th>
                        <th>项目名</th>
                        <th>价格</th>
                        <th>支付状态</th>
                        <th>操作</th>
                    </tr>
                    {% for foo in pay %}
                    <tr>
                        <td>{{foo.project.Order_ID}}</td>
                        <td>{{foo.project.name}}</td>
                        <td>{{foo.price}}</td>
                        <td>{% if foo.is_pay %}已支付 {% else %}未支付{% endif %}</td>
                        <td>{% if not foo.is_pay %}<a href="">支付</a>{% else %}<a href="">查看</a>{% endif %}</td>
                    </tr>
                    {% endfor %}
                    </thead>
     </table>
{% endblock %}

webuser/templates/webuser/person_page.html
{% extends "base.html"%}
{% block title%} 个人主页 {% endblock%}


{% block page_content %}
    <!--主题内容-->
        <div id="mainbody">
        <div class="container">
            <div class="row">
            <div class="col-md-3">
                <div class="sidebar">
                <div class="list-group">
                    <a class="list-group-item selected" href="/person/">个人资料</a>
                    <a class="list-group-item selected" href="/project">工程管理</a>
                    <a class="list-group-item selected" href="/pay">支付管理</a>
                    <a class="list-group-item selected" href="http://qiangben.com/">关于我们</a>
                    <a class="list-group-item selected" href="#">意见反馈</a>
                </div>
                </div>
            </div>

                <!--显示左边菜单点击后的内容-->
                <div class="col-md-9">
                    <div class="container">
                    {%block person_home_content%}
                        <!--显示个人主页中间主要内容-->
                        <!--end-->
                    {%endblock%}
                    </div>
                </div>

            </div>

        </div>
            </div>
    <!--主题内容结束-->


{% endblock%}

webuser/templates/webuser/person_page_info.html
{% extends 'webuser/person_page.html' %}
{% block title %}个人主页个人资料页面{% endblock %}
{% block person_home_content %}
    <div class="col-md-6 container">
        <h1 class="page-header"><small>个人资料</small></h1>

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}x
      {% endif %}
{# 删掉了action="petson" 以防链接生成的时候的错误 #}
            <form role="form" class="ProfileForm "  method="post" role="form">
                  {% csrf_token %}
                <fieldset>
                    {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.label }}">{{ field.label }}</label>
          {{ field }}
          {% if field.help_text %}
            <span class="help-block">{{ field.help_text|safe }}</span>
          {% endif %}
          {% for error in field.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
      {% endfor %}
                </fieldset>

        <div class="form-group">
            <div  class="form-group-left">
              <button type="submit" class="btn btn-large btn-primary">提交资料</button>

              </div>
          </div>
             </form>
        <button class="btn btn-large btn-primary" onclick="javascript:change_passwords()">修改密码</button>
        </div>

{% endblock %}

webuser/templates/webuser/project_create.html
{% extends 'webuser/person_page.html' %}
{% block title %}个人主页个人资料页面{% endblock %}
{% block person_home_content %}
    <div class="col-md-6 container">
        <h1 class="page-header"><small>创建项目</small></h1>

      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}

            <form role="form" class="ProjectForm " method="post" role="form">
                  {% csrf_token %}
                <fieldset>
                    {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.label }}">{{ field.label }}</label>
        {% if field.name == 'Oder_id' %}
            <div style="display: none;" >{{ field }}</div>
        {% elif field.name == 'dir'%}
          <div style="display: none;" >{{ field }}</div>
            <div class="demo-box">
    <input id="file_upload" type="file" name="Filedata">
    <div id="file_uploadQueue" class="uploadifyQueue"></div>
     <a href="javascript:$('#file_upload').uploadify('upload','*')">上传</a>
    <p><span id="id_span_msg"></span></p>
            </div>
         {% else %}
            {{ field }}
        {% endif %}
          {% if field.help_text %}
            <span class="help-block">{{ field.help_text|safe }}</span>
          {% endif %}
          {% for error in field.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
      {% endfor %}
        {% for field in form.visible_fields %}
                {% for error in field.errors %}
                    <script>
                 $("#id_dir").val("");
                    //这里的for循环就需要很注意，form表单展示出来的时候就是for循环，所以在for循环没循环到指定位置的时候，
                    //对这个指定位置所做的操作是无效的，比如这里，想要触发清空dir字段的操作，必须要在上面的for循环结束之后
                    //再做，因为就算是在for循环里dir字段之前的字段发生错误触发这个清空操作，dir字段的id是找不到的，因为它还没有
                    //被展示在网页里，所以只有在所有的filed展示出来，即以代码的形式通过for循环展示到网页中之后，定位dir字段id的
                    //的操作才会绝对有效
              </script>
                {% endfor %}
                {% endfor %}

                </fieldset>

        <div class="form-group">
            <div  class="form-group-left">
              <button type="submit" class="btn btn-large btn-primary">提交资料</button>

              </div>
          </div>

             </form>
        </div>
{% endblock %}

webuser/templates/webuser/project_manage.html
{% extends 'webuser/person_page.html' %}
{% block title %}个人主页个人资料页面{% endblock %}
{% block person_home_content %}
    <style type="text/css">
table.gridtable {
	font-family: verdana,arial,sans-serif;
	font-size:11px;
	color:#333333;
	border-width: 1px;
	border-color: #666666;
	border-collapse: collapse;
}
table.gridtable th {
	border-width: 1px;
	padding: 10px;
	border-style: solid;
	border-color: #666666;
	background-color: #dedede;
}
table.gridtable td {
	border-width: 1px;
	padding: 8px;
	border-style: solid;
	border-color: #666666;
	background-color: #ffffff;
}
</style>
        <h1 class="page-header"><small>工程管理</small></h1>

     <table class="gridtable" cellpadding="0" cellspacing="0" >
                    <thead>
                    <tr>
                        <th>项目编号</th>
                        <th>项目名</th>
                        <th>项目类别</th>
                        <th>创建时间</th>
                        <th>完成状态</th>
                        <th>操作</th>
                    </tr>
                    {% for foo in project %}
                    <tr>
                        <td>{{foo.Order_ID}}</td>
                        <td>{{foo.name}}</td>
                        <td>{{foo.classify}}</td>
                        <td>{{foo.create_time|date:"Y-m-d H:i:s" }}</td>

                        </td>

                        <td>{% if foo.status %}
                            已完成
                            {% else %}
                            未完成
                        {% endif %}</td>

                        <td>
                            <a href="javascript:deleteProject({{foo.Order_ID}})">删除</a>
                            {% if foo.status %}
                                <a href="">查看</a>
                                {% else %}
                                查看
                            {% endif %}
                            <a href="javascript:change_peoject({{ foo.Order_ID }})">修改</a>
                        </td>

                    </tr>
                    {% endfor %}
                    </thead>

     </table>
<br> </br>
    <div class="form-group">
            <div  class="form-group-left">
              <button type="submit" class="btn btn-large btn-primary" onclick="javascript:createProject()">新建项目</button>

              </div>
          </div>
       <script>
         function change_peoject(oder_id) {
             location.href = "/change_project/?oder_id="+oder_id;
      }

    function deleteProject(orderId) {
        if (confirm("您确定要删除么，记录删除后将无法找回")) {
            location.href = "/delete_project?orderId=" + orderId + "";
        }
    }
    function createProject() {
            location.href = "/create_project";
    }
</script>
{% endblock %}

webuser/templates/webuser/register.html
{% extends "base.html" %}
{% block title %}NOMOVIE-Register {% endblock %}
{% block page_content %}

<div id="mainbody">
         <div class="container">
            <h1 class="page-header">注册</h1>
             <div class="col-md-6">
             <form role="form" class="registerForm" action="{% url 'register' %}" method="post" role="form">
                  {% csrf_token %}
                <fieldset>
                    {% for field in form.visible_fields %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label for="{{ field.label }}">{{ field.label }}</label>
          {{ field }}
          {% if field.help_text %}
            <span class="help-block">{{ field.help_text|safe }}</span>
          {% endif %}
          {% for error in field.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
      {% endfor %}

                </fieldset>

        <div class="form-group">
            <div  class="form-group-left">
              <button type="submit" class="btn btn-large btn-primary">创建账户</button>

              </div>
          </div>
             </form>
                 </div>
         </div>
</div>
{% endblock %}